version: "3.9"
services:
  db:
    image: "bitnami/mongodb:latest"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "27017:27017"
